events {}

http {
  server {
    listen 8080;

    location = /styles/redirect.css {
      return 302 /styles/redirect-hop.css;
    }

    location = /styles/redirect-hop.css {
      return 302 http://frontend:3000/styles/redirect.css;
    }

    location /api/v2/recommendations {
      if ($http_origin = "http://localhost:3000") {
        add_header Access-Control-Allow-Origin "";
      }
      proxy_pass http://backend:3001;
    }

    location / {
      proxy_pass http://frontend:3000;
    }
  }

  server {
    listen 3443 ssl;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

    location /socket.io/ {
      proxy_pass http://backend:3001;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
